version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: default
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
